In [2]:
import pandas as pd
import numpy as np 
import os

In [62]:
df = pd.read_csv('total_data_v1_0707.csv')
print(df.shape)
print(df.columns)
df.head(10)

/var/folders/n2/47w8btw54tj424xjtwbffw3c0000gn/T/ipykernel_401/3145374390.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('total_data_v1_0707.csv')


(628398, 17)
Index(['Lot number', 'Winning bid', 'age', 'auction', 'bottle number',
       'bottled', 'cask number', 'cask type', 'distilled',
       'extracted_distillery', 'his_bid_prices', 'his_bid_times', 'name',
       'strength', 'url', 'url_id', 'cl'],
      dtype='object')


Lot number  Winning bid   age  auction  bottle number  bottled  cask number  \
0     620119         55.0   NaN      100            NaN      NaN          NaN   
1     621531         55.0   NaN      100            NaN      NaN          NaN   
2     622681         55.0   NaN      100            NaN      NaN          NaN   
3     622979         55.0   NaN      100            NaN      NaN          NaN   
4     622168        720.0  13.0      100            NaN   2012.0       6697.0   
5     622169        720.0  17.0      100            NaN   2013.0         26.0   
6     620009         90.0   NaN      100            NaN      NaN          NaN   
7     620008         95.0   NaN      100            NaN      NaN          NaN   
8     620010         95.0   NaN      100            NaN      NaN          NaN   
9     620302         95.0   NaN      100            NaN      NaN          NaN   

     cask type  distilled extracted_distillery  \
0          NaN        NaN             macallan   
1          NaN        NaN             macallan   
2          NaN        NaN             macallan   
3          NaN        NaN             macallan   
4  Sherry Butt     1999.0             macallan   
5  Sherry Butt     1996.0             macallan   
6          NaN        NaN             macallan   
7          NaN        NaN             macallan   
8          NaN        NaN             macallan   
9          NaN        NaN             macallan   

                                      his_bid_prices  \
0  [130.0, 88.33, 61.0, 47.5, 48.33, 45.0, 43.75,...   
1  [130.0, 88.33, 61.0, 47.5, 48.33, 45.0, 43.75,...   
2  [130.0, 88.33, 61.0, 47.5, 48.33, 45.0, 43.75,...   
3  [130.0, 88.33, 61.0, 47.5, 48.33, 45.0, 43.75,...   
4  [860.0, 533.33, 540.0, 590.0, 600.0, 476.67, 5...   
5  [540.0, 506.67, 615.0, 580.0, 620.0, 566.67, 5...   
6  [165.0, 180.0, 111.67, 108.89, 67.78, 95.83, 7...   
7  [165.0, 180.0, 111.67, 108.89, 67.78, 95.83, 7...   
8  [165.0, 180.0, 111.67, 108.89, 67.78, 95.83, 7...   
9  [165.0, 180.0, 111.67, 108.89, 67.78, 95.83, 7...   

                                       his_bid_times  \
0  [24.0, 25.0, 26.0, 28.0, 29.0, 31.0, 33.0, 34....   
1  [24.0, 25.0, 26.0, 28.0, 29.0, 31.0, 33.0, 34....   
2  [24.0, 25.0, 26.0, 28.0, 29.0, 31.0, 33.0, 34....   
3  [24.0, 25.0, 26.0, 28.0, 29.0, 31.0, 33.0, 34....   
4  [22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29....   
5  [33.0, 34.0, 36.0, 37.0, 43.0, 44.0, 45.0, 49....   
6  [57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64....   
7  [57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64....   
8  [57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64....   
9  [57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64....   

                           name  strength  \
0   Macallan Director's Edition      40.0   
1   Macallan Director's Edition      40.0   
2   Macallan Director's Edition      40.0   
3   Macallan Director's Edition      40.0   
4  Macallan Easter Elchies 2012      57.2   
5  Macallan Easter Elchies 2013      55.3   
6          Macallan Edition No1      48.0   
7          Macallan Edition No1      48.0   
8          Macallan Edition No1      48.0   
9          Macallan Edition No1      48.0   

                                                 url  url_id    cl  
0  https://www.scotchwhiskyauctions.com/auctions/...  100333  70.0  
1  https://www.scotchwhiskyauctions.com/auctions/...  101847  70.0  
2  https://www.scotchwhiskyauctions.com/auctions/...  103100  70.0  
3  https://www.scotchwhiskyauctions.com/auctions/...  103453  70.0  
4  https://www.scotchwhiskyauctions.com/auctions/...  102514  70.0  
5  https://www.scotchwhiskyauctions.com/auctions/...  102515  70.0  
6  https://www.scotchwhiskyauctions.com/auctions/...   95219  70.0  
7  https://www.scotchwhiskyauctions.com/auctions/...   95218  70.0  
8  https://www.scotchwhiskyauctions.com/auctions/...   95220  70.0  
9  https://www.scotchwhiskyauctions.com/auctions/...  100608  70.0

In [63]:
from collections import Counter 
stats = Counter(df['url_id'].astype(str))
dup_keys = []
dup_vs = []
for k,v in stats.items():
    if v > 1:
        dup_keys.append(k)
        dup_vs.append(v)
        # print(k,v)
print(len(dup_keys),dup_keys[:5])
print(np.unique(dup_vs))

1968 ['102790', '103002', '101169', '100585', '103225']
[2 3 4 5 6]


In [163]:
# remove duplicate datas 
newdf = df.drop_duplicates('url',keep='first')
print(newdf.shape)

(626285, 17)


In [164]:
np.percentile(newdf[newdf['Winning bid'].notna()]['Winning bid'].astype(np.float32),range(0,105,5))

array([5.0e+00, 2.5e+01, 3.5e+01, 4.0e+01, 5.0e+01, 5.5e+01, 6.5e+01,
       7.5e+01, 8.0e+01, 9.0e+01, 1.0e+02, 1.2e+02, 1.3e+02, 1.5e+02,
       1.7e+02, 2.1e+02, 2.5e+02, 3.2e+02, 4.6e+02, 8.2e+02, 2.0e+05])

In [165]:
print(np.sum(newdf['bottled'].notna().values),
np.sum(newdf['distilled'].notna().values))
with_val = newdf['distilled'].notna().values & newdf['bottled'].notna().values
np.sum(with_val)

221947 196676


150902

In [166]:
newdf['age']

0          NaN
1          NaN
2          NaN
3          NaN
4         13.0
          ... 
628393    10.0
628394    12.0
628395    17.0
628396    17.0
628397    17.0
Name: age, Length: 626285, dtype: float64

In [167]:
need_fill = newdf['age'].isna().values & with_val
print(np.sum(newdf['age'].notna().values),np.sum(need_fill))

324892 49935


In [168]:
newdf[need_fill]['bottled'].min(),newdf[need_fill]['bottled'].max(), newdf[need_fill]['distilled'].min(),newdf[need_fill]['distilled'].max()

(1812.0, 2023.0, 1805.0, 2022.0)

In [169]:
newdf.loc[need_fill,'age'] = newdf[need_fill]['bottled'].values - newdf[need_fill]['distilled'].values

In [170]:
print(np.sum(newdf['age'].notna().values))

374827


In [171]:
newdf = newdf.drop(columns=['bottled','distilled','Lot number'])

In [172]:
np.percentile(newdf[newdf['age'].notna()]['age'],range(0,105,5))

array([-183.,    7.,    9.,   10.,   10.,   12.,   12.,   12.,   13.,
         14.,   15.,   16.,   18.,   18.,   20.,   21.,   22.,   25.,
         27.,   31., 5000.])

In [173]:
newdf.shape

(626285, 14)

In [174]:
newdf = newdf[True ^ (newdf['age']<0)]
newdf = newdf[True ^ (newdf['age']>300)]
newdf = newdf[True ^ (newdf['Winning bid']>1000)]
print(newdf.shape)

(603496, 14)


In [182]:
newdf.to_csv('data_all_v2.csv',index=False)